name: dl_constants.php maintainer
on:
  release:
    types: [published]
    branches: ["main"]
jobs:
  update-backend-files:
    name: Update plugin version & download url
    if: '!github.event.release.prerelease'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: 'necodeIT/lb_planner_web'
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: Update plugin url
        run: sed -i '/dl_plugin/c\const dl_plugin = "${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/lb_planner.zip";' /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/snippets/dl_constants.php

      - name: Update plugin comment
        run: sed -i '/Plugin download url/c\ * Plugin download url [@${{ github.event.release.tag_name }}](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}).' /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/snippets/dl_constants.php

      - name: Commit & Push
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.REPO_WEB_TOKEN }}
          repository: 'necodeIT/lb_planner_web'
          branch: main
          message: "Github Actions - Updated dl_constants.php to ${{ github.event.release.tag_name }}"
      - name: SFTP Upload to Webserver
        uses: Dylan700/sftp-upload-action@v1.1.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          uploads: |
            snippets/dl_constants.php => /htdocs/snippets/dl_constants.php
