name: Generate API Docs

on:
  push:
    branches:
      - LP-55-Backend-Refactor # This is temporary and will be replaced by `moodle` once the refactor is complete
  workflow_dispatch: # For manual triggering

jobs:
  generate-api-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: LP-55-Backend-Refactor # This is temporary and will be replaced by `moodle` once the refactor is complete
          path: moodle

      - name: Checkout docs branch
        uses: actions/checkout@v3
        with:
          ref: docs
          clean: false
          path: docs

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'

      - name: Clear old documentation in /moodle subdir
        run: |
          rm -f docs/moodle/script.js

      - name: Generate docs
        working-directory: moodle
        run: python document_services.py ../docs/moodle

      - name: Push new documentation to docs branch
        working-directory: docs
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add -A
          git commit -m "GitHub Actions - Update Web Service Documentation to ${{ github.sha }}"
          git push
