name: Generate API Docs

on:
  push:
    branches:
      - main
  workflow_dispatch: # For manual triggering

jobs:
  generate-api-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: main
          path: moodle

      - name: Checkout docs repo
        uses: actions/checkout@v3
        with:
          repository: 'necodeIT/lb_planner_docs'
          ref: main
          clean: false
          path: docs
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.12'

      - name: Generate docs
        working-directory: moodle
        run: python document_services.py ../docs/moodle

      - name: Push new documentation to docs repo
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.REPO_DOCS_TOKEN }}
          repository: 'necodeIT/lb_planner_docs'
          branch: main
          message: "GitHub Actions - Update Web Service Documentation to ${{ github.sha }}"
          directory: docs
