name: Generate API Docs

on:
  push:
    branches:
      - main
  workflow_dispatch: # For manual triggering

jobs:
  generate-api-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main
          path: moodle

      - name: Checkout docs repo
        uses: actions/checkout@v4
        with:
          repository: 'necodeIT/lb_planner_docs'
          ref: main
          clean: false
          path: docs
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate docs
        working-directory: moodle
        run: python document_services.py ../docs/moodle

      - name: Commit changes
        working-directory: docs
        run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -a -m "GitHub Actions - Update Web Service Documentation"

      - name: Push new documentation to docs repo
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.REPO_DOCS_TOKEN }}
          branch: main
          directory: docs
