name: API Doc Parsing

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  generate-api-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: moodle

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.12'

      - name: Generate docs
        working-directory: moodle
        run: python document_services.py -
